### 1. 회원 등록
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "user",
  "pw": "user@pass",
  "name": "일반유저",
  "phone": "010-1234-1234"
}

### 1. 회원 등록2
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "admin",
  "pw": "admin@pass",
  "name": "관리자",
  "phone": "010-1234-1234",
  "grade": "admin"
}

### 1. 회원 등록3
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "yeardream",
  "pw": "year@dream",
  "name": "오헌제",
  "phone": "010-3344-5978"
}

### 1. 회원 등록4
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "manager",
  "pw": "manager@pass",
  "name": "오헌제",
  "phone": "010-3344-5978"
}

### 2. 회원 목록
GET http://localhost/member/list

### 3. 회원 상세보기
GET http://localhost/member/get/admin2

### 4. 회원 수정
PUT http://localhost/member/update/admin
Content-Type: application/json

{
  "name": "관리다(수정된 이름)",
  "grade": "admin"
}

### 5. 회원 삭제
DELETE http://localhost/member/delete/yeardream