### 1. 회원 등록1 (일반 유저)
POST http://localhost:3000/member/join
Content-Type: application/json

{
  "id": "user",
  "pw": "user@pass",
  "name": "일반유저",
  "phone": "010-1234-1234"
}

### 1. 회원 등록2 (관리자)
POST http://localhost:3000/member/join
Content-Type: application/json

{
  "id": "admin",
  "pw": "admin@pass",
  "name": "관리자",
  "phone": "010-1234-1234",
  "grade": "admin"
}

### 1. 회원 등록3
POST http://localhost:3000/member/join
Content-Type: application/json

{
  "id": "yeardream",
  "pw": "year@dream",
  "name": "오헌제",
  "phone": "010-3344-5978"
}

### 1. 회원 등록4
POST http://localhost:3000/member/join
Content-Type: application/json

{
  "id": "manager",
  "pw": "manager@pass",
  "name": "오헌제",
  "phone": "010-3344-5978"
}

### 1. 회원 등록5 (ID 중복 수정: manager -> manager2)
POST http://localhost:3000/member/join
Content-Type: application/json

{
  "id": "manager2",
  "pw": "manager@pass",
  "name": "크리스티나",
  "phone": "010-2323-4545"
}

### 2. 회원 목록 조회
GET http://localhost:3000/member/list

### 3. 회원 상세보기 (아이디 수정: admin2 -> admin)
GET http://localhost:3000/member/get/admin

### 4. 회원 수정
PUT http://localhost:3000/member/update/admin
Content-Type: application/json

{
  "name": "관리자(수정된 이름)",
  "grade": "admin"
}

### 5. 회원 삭제
DELETE http://localhost:3000/member/delete/yeardream